In [10]:
import numpy as np
import time

In [15]:
#list vs numpy

#execution performance
size = 100_000_000

#python list
py_list = list(range(size)) 
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end-start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr ** 2
end = time.time()
print(f"python list time = {end-start} seconds")

python list time = 10.098971843719482 seconds
python list time = 0.3225398063659668 seconds


In [17]:
#memory
import sys
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")

print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 80000005600000000 bytes
numpy array size = 800000000 bytes


In [21]:
#create numpy - from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr))

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2), arr2.dtype,arr2.shape)

arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D ,type(arr2D), arr2D.dtype, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [36]:
#creating numpy array from scratch
arr1 = np.zeros((2,3)) #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5,)) #prefill
print(arr2, arr2.shape)

arr3 = np.full((3,4,),100) #prefill with val
print(arr3, arr3.shape)

arr4 = np.eye(3) #identityy matrix
print(arr4, arr4.shape)

arr5 = np.arange(1,11,2) #prefill with val
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4) #prefill with val
print(arr6, arr6.shape)




[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [40]:
#properties of np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr , float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [43]:
#operation on arrays

arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshape = arr.reshape((3,2))
print(reshape, reshape.shape)

flattenend = arr.flatten()
print(flattenend, flattenend.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [45]:
#Slicing
arr = np.array([1,2,3,4,5])

print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [55]:
#copy vs view
# nums = [1,2,3,4,5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200

# print(sub_list)
# print(nums)


arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] =200

print(sub_arr)
print(arr)


[2 3]
[200   3]
[  1 200   3   4   5]
