In [1]:
import numpy as np
import time

In [7]:
#datatypes

arr = np.array([1,2,3,4,5])
print(arr, arr.dtype)

arrr = np.array([1,2,3,4,"prime"])
print(arrr, arrr.dtype)

ar = np.array([3+5j])
ar1 = np.array([2+3j])

print(ar +ar1)
print(ar-ar1)
print(ar, ar.dtype)

arr1r = np.array(["prime", {1,2,3}, 3.14])
print(arr1r, arr1r.dtype)

[1 2 3 4 5] int64
['1' '2' '3' '4' 'prime'] <U21
[5.+8.j]
[1.+2.j]
[3.+5.j] complex128
['prime' {1, 2, 3} 3.14] object


In [15]:
#multidimensional arrays

arr2d = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(arr2d)

print(np.sum(arr2d))
sum_of_columns = np.sum(arr2d, axis = 0)
print(sum_of_columns)
sum_of_rows=(np.sum(arr2d,axis =1))
print(sum_of_rows)

print(arr2d[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [27]:
#3D array
arr3D = np.array([[[1,2],[3,4],[5,6]], [[7,8],[9,10],[11,12]]])#2x3x2

print(arr3D, arr3D.shape)

#indexing
print(arr3D[1,1,0])

#slicing
print(arr3D[:,0,:])#first row from bot
print(arr3D[:,:,0])#first column form both
arr3D[:,0,:]=99 #row manipulation
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [30]:
#vectorization
arr = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr ** 2)
print(arr +10)
print(arr +arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [33]:
#Broadcasting

print(arr +5)
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr.shape)
print(arr2.shape)
print(arr +arr2)

[ 6  7  8  9 10]
(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [38]:
#normalize
arr = np.array([[1,2], [3,4]])

mean =np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [41]:
#mathematical fnx

#aggregation
arr =np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmax(arr))
print(np.argmin(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
4
0
3.0
1.4142135623730951
3.0
2.0


In [43]:
#power fnx
arr =np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [45]:
#log

arr =np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [52]:
#rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr =np.array([1,2,-8,-3,5,4,2,4,5])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))


3.0
4.0
3.0
3.0
[-8 -3  1  2  4  5]
[-8 -3  1  2  2  4  4  5  5]
[1 2 8 3 5 4 2 4 5]
